name: DEPLOY
on:
  push:
    branches:
      - release
jobs:
  ci:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: ./gradlew :linkt:assembleRelease

      - name: Publish
        run: ./gradlew -Puser=${{ secrets.BINTRAY_USER }} -Pkey=${{ secrets.BINTRAY_TOKEN }} :linkt:bintrayUpload